server-name: "lobby-1"
spawn-location: ""

welcome-message:
  - "&7&m----------------------------------------"
  - "&fWelcome &e%player% &fto &6&lServer Network"
  - ""
  - " &a&l┃ Store &fstore.server.net"
  - " &9&l┃ Discord &fdiscord.server.net"
  - " &b&l┃ Twitter &f@ServerNetwork"
  - "&7&m----------------------------------------"

chat-system:
  enabled: true
  format: "&7%player% &8» &7%message%"

boss-bar-system: # NOT AVAILABLE IN 1.8
  enabled: true
  types:
    example-1:
      title: "&aExample #1 | Boss Bar"
      color: GREEN
      style: SOLID
    example-2:
      title: "&cExample #2 | Boss Bar"
      color: RED
      style: SOLID
    example-3:
      title: "&bExample #3 | Boss Bar"
      color: BLUE
      style: SOLID

pvp-mode:
  enabled: true
  activation:
    mode: "cooldown" # instant | cooldown
    cooldown_seconds: 5
  sword:
    slot: 4
    name: "&cCombat Sword"
    lore:
      - "&7Use this sword to fight"
      - "&7Get ready for combat"
    material: DIAMOND_SWORD
    enchants:
      damage_all: 3
  combat:
    duration_seconds: 15
  equipment:
    helmet:
      name: "&cBattle Helmet"
      material: DIAMOND_HELMET
      enchants:
        protection_environmental: 2
    chestplate:
      name: "&cBattle Chestplate"
      material: DIAMOND_CHESTPLATE
      enchants:
        protection_environmental: 2
    leggings:
      name: "&cBattle Leggings"
      material: DIAMOND_LEGGINGS
      enchants:
        protection_environmental: 2
    boots:
      name: "&cBattle Boots"
      material: DIAMOND_BOOTS
      enchants:
        protection_environmental: 2
  spawn:
    enabled: false
    location: ""

parkour-system:
  enabled: true
  streak:
    points-intervals: 10 #
    # List of commands to be executed when the streak is achieved
    # Use without the key "/"
    # Placeholder %target%
    # For example:
    # - give %target% <item> <amount>
    commands: {}
  generator:
    # Possible attempts to generate a new block, reference value: 20
    attempts: 20
    # It is recommended to use a minimum distance of 1 and a maximum of 4 to avoid problems and errors.
    min-distance: 2
    max-distance: 3
    # Here you can place as many blocks as you want
    # Latest Versions: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    # Legacy Versions: https://helpch.at/docs/1.8.8/index.html?org/bukkit/Material.html
    # Format -> Latest: <id>
    # Format -> Legacy: <id> or <id;data>
    # Recommendation: place solid blocks
    block-materials:
      - 'OBSIDIAN'
      - 'NOTE_BLOCK'
      - 'SANDSTONE'
      - 'DIAMOND_BLOCK'
      - 'TNT'