name: '${project.artifactId}'
version: '${project.version}'
main: studio.overmine.overhub.OverHub
api-version: '1.13'
author: "OverMine Studios"
depend: [PlaceholderAPI, packetevents]
commands:
  overhub:
    permission: "overhub.command.overhub"
    description: "OverHub command"
    aliases: ["oh"]
  spawn:
    description: "Spawn command"
  setspawn:
    permission: "overhub.command.setspawn"
    description: "Set spawn command"
  parkour:
    permission: "overhub.command.parkour"
    description: "Parkour command"
  pvp:
    permission: "overhub.command.pvp"
    description: "PvP command"
    aliases: ["combat"]
  gamemode:
    permission: "overhub.command.gamemode"
    description: "Gamemode command"
    aliases: ["gm"]
  fly:
    permission: "overhub.command.fly"
    description: "Fly command"
  heal:
    permission: "overhub.command.heal"
    description: "Heal command"
    aliases: ["health"]
  feed:
    permission: "overhub.command.feed"
    description: "Feed command"
  clearinventory:
    permission: "overhub.command.clearinventory"
    description: "Clear inventory command"
    aliases: ["ci", "clear"]
  tpall:
    permission: "overhub.command.tpall"
    description: "Teleport all players command"
  tp:
    permission: "overhub.command.tp"
    description: "Teleport command"
    aliases: ["teleport"]
  tphere:
    permission: "overhub.command.tphere"
    description: "Teleport here command"
    aliases: ["tph"]

